### ISSUE TITLE
Uploading LPIS data permissions error

### ISSUE THREAD

**Issue by kalxas** [Sen4CAP/sen4cap-services#1]
Hi,
We are facing an error when we upload an LPIS shapefile:
![image](https://user-images.githubusercontent.com/383944/72602243-9e403980-391f-11ea-8dfe-3b829c5072db.png)

Looks like the folder gets created in /mnt/uploads/[site] folder but with ownership by apache user and cannot be moved to the /mnt/uploads/lpis/ folder by the sen4cap user.

Any workarounds?

**Comment by lnicola** [comment]
Sorry for this. I'll have to look more into it, but a quick workaround would be to run `chmod -R 777 /mnt/archive/uploads`. `chown  -R apache: /mnt/archive/uploads` might also work.

**Comment by kalxas** [comment]
I have tried both before sending the issue, the problem is that the uploaded folder is created as apache and the default permissions is 644, so the sen4cap user fails to move it to another folder.

**Comment by lnicola** [comment]
I'm not sure why another system user tries to move the directory. You could also `chmod -R 777 /mnt/upload`? That way the other user should be able to move it.

**Comment by kalxas** [comment]
so if I understand correctly, all file manipulation actions happen from the apache user?

**Comment by lnicola** [comment]
I would have to check, but that was my original assumption. But if another system user tries to move the files from the original upload folder, making it `777` should prevent the permissions error.

That's because moving `/mnt/upload/foo/` to `/mnt/other/bar/` requires:
 - write access to `/mnt/other/bar` in order to be able to create the destination
 - write access to `/mnt/upload` in order to be able to remove `foo` from it

**Comment by kalxas** [comment]
I have provided 777 to all folders under /mnt/archive and /mnt/upload and I get the same error:

![image](https://user-images.githubusercontent.com/383944/72666442-ff990300-3a1a-11ea-920d-7f8d5038deb6.png)

Here are the folder permissions in the setup:

![image](https://user-images.githubusercontent.com/383944/72666490-66b6b780-3a1b-11ea-80e6-9b7faa78e919.png)

**Comment by kalxas** [comment]
I also changed owner to sen2agri-service:

![image](https://user-images.githubusercontent.com/383944/72666574-72ef4480-3a1c-11ea-8426-059e59aa64d9.png)

and get the same error.

That tells me that files are uploaded with default 644 permissions from apache user but the move is happening from sen2agri-service user which does not have permission to move the /mnt/upload/test_site_1/sen4cap_1580942568141 folder

**Comment by kalxas** [comment]
While uploading files I changed the permission of the uploaded folder to 777 and I get the same error, so the problem must be something else.

**Comment by kalxas** [comment]
It looks like the files actually get uploaded in /mnt/archive/upload/lpis/test_site_1/

![image](https://user-images.githubusercontent.com/383944/72667923-b43a2100-3a29-11ea-8e18-4f8ad66f0f76.png)

A new folder is getting created as can be seen in the terminal. Can this be a timeout error being thrown because it is taking more time to copy than expected?

**Comment by kalxas** [comment]
Thank you @lnicola for your help, I managed to fix the problem, it was related to the permissions of the files uploaded in the zip file.

**Comment by lnicola** [comment]
I'm glad you got it fixed. We should test a similar scenario and validate the uploaded files or fix their permissions, because it seems impossible to debug otherwise.

**Comment by kalxas** [comment]
yes, I had to make sure the files were a+rwx and the zip file not containing a folder, just plain files.
